{% set name = "kvh" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kvh-{{ version }}.tar.gz
  sha256: 77ab59023dfb3ba66c9ef2929cbef06ddc2ea94ca17f61084537cef13d1dd0cc

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pybind11
    - pip
    - meson-python
    - ninja
    - pkg-config
    - python-build
    - cython
  run:
    - python

test:
  imports:
    - kvh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://forgemia.inra.fr/mathscell/kvh
  summary: KVH format reader/writer
  dev_url: https://forgemia.inra.fr/mathscell/kvh
  license: GPL-2.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgsokol
